import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { ChevronDown, Sparkles } from "lucide-react";

import { CodeBlock } from "@/components/CodeBlock";
import { CopyButton } from "@/components/CopyButton";
import { BODY, CAPTION } from "@/components/style-tokens";
import {
  PLACEHOLDER_SLUG,
  profileAgentPrompt,
  repoAgentPrompt,
  starFacts,
  type StarFacts,
} from "@/lib/agent-prompt";
import {
  DURATION,
  EASE_OUT,
  REDUCED_MOTION_DURATION,
} from "@/lib/motion";
import { cn } from "@/lib/utils";

type RepoTarget = { kind: "repo"; slug: string; stars?: StarFacts | null };
type ProfileTarget = {
  kind: "profile";
  login: string;
  totalStars?: number | null;
  reposIncluded?: number | null;
};
/** No repository in hand: the prompt resolves one from the checkout's remote. */
type GenericTarget = { kind: "generic" };

export type PromptTarget = RepoTarget | ProfileTarget | GenericTarget;

type Props = {
  apiBase: string;
  siteOrigin: string;
  target: PromptTarget;
};

/** The analyze payload `RepoHero` broadcasts once live data lands. */
type RepoDataEvent = {
  repo?: string;
  total_stars?: number;
  history_kind?: string;
  history_approximate?: boolean;
  history?: { date: string; stars: number }[];
};

/**
 * "Ask an agent to add this to my repo".
 *
 * The copied text is a complete brief, not a one-liner: measured numbers so the
 * agent never invents a statistic, exact paste-ready snippets, the rules that
 * make a published embed correct, and the places to look beyond `README.md`.
 * It is generated by the same pure module that writes the `.md` representation
 * of this page, so what a person copies and what an agent fetches agree.
 *
 * Star facts arrive prerendered and are refreshed from the report's own
 * `gitdebt:repo-data` broadcast — this component never issues a request of its
 * own.
 */
export function AgentReadmePrompt({ apiBase, siteOrigin, target }: Props) {
  const [live, setLive] = useState<StarFacts | null>(null);
  const [open, setOpen] = useState(false);
  const reduceMotion = useReducedMotion();

  const slug = target.kind === "repo" ? target.slug : null;

  useEffect(() => {
    if (!slug) return;
    function absorb(event: Event) {
      const detail = (event as CustomEvent<RepoDataEvent>).detail;
      if (detail?.repo?.toLowerCase() !== slug!.toLowerCase()) return;
      if (!Array.isArray(detail.history)) return;
      setLive(
        starFacts(
          detail.history,
          detail.total_stars ?? null,
          detail.history_kind === "public_star_actions" ||
            detail.history_approximate === true,
        ),
      );
    }
    window.addEventListener("gitdebt:repo-data", absorb);
    return () => window.removeEventListener("gitdebt:repo-data", absorb);
  }, [slug]);

  const prompt = useMemo(() => {
    if (target.kind === "profile") {
      return profileAgentPrompt({
        login: target.login,
        siteOrigin,
        apiBase,
        totalStars: target.totalStars ?? null,
        reposIncluded: target.reposIncluded ?? null,
      });
    }
    return repoAgentPrompt({
      slug: target.kind === "repo" ? target.slug : PLACEHOLDER_SLUG,
      siteOrigin,
      apiBase,
      stars: target.kind === "repo" ? (live ?? target.stars ?? null) : null,
    });
  }, [apiBase, siteOrigin, target, live]);

  const action =
    target.kind === "profile"
      ? "Ask agent to add this to my profile"
      : "Ask agent to add this to my repo";

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-3">
        <CopyButton
          value={prompt}
          ariaLabel="Copy an agent prompt that adds these embeds to a README"
          idleLabel={action}
          successLabel="Prompt copied"
          idleIcon={<Sparkles className="size-3.5" strokeWidth={2} />}
          variant="primary"
          size="default"
        />
        <button
          type="button"
          onClick={() => setOpen((value) => !value)}
          aria-expanded={open}
          className={cn(
            CAPTION,
            "inline-flex items-center gap-1.5 rounded outline-none transition-colors duration-150 hover:text-foreground focus-visible:ring-2 focus-visible:ring-accent/30",
          )}
        >
          {open ? "Hide the prompt" : "Read the prompt first"}
          <ChevronDown
            className={cn(
              "size-3.5 transition-transform duration-200 motion-reduce:transition-none",
              open && "rotate-180",
            )}
            aria-hidden="true"
          />
        </button>
      </div>

      <p className={cn(BODY, "max-w-[68ch]")}>
        Paste it into Claude Code, Cursor, Codex, or any coding agent with your
        checkout open. It carries the measured numbers, the exact snippets, and
        the rules — including replacing an existing star-history widget in place
        rather than stacking a second chart under it.
      </p>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ opacity: 0, y: reduceMotion ? 0 : -4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: reduceMotion ? 0 : -3 }}
            transition={{
              duration: reduceMotion ? REDUCED_MOTION_DURATION : DURATION.enter,
              ease: EASE_OUT,
            }}
          >
            <CodeBlock
              code={prompt}
              language="markdown"
              label="Agent prompt"
              copyLabel="Copy prompt"
              copyAriaLabel="Copy the agent prompt"
              maxHeightClass="max-h-96"
            />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
