import { useEffect, useMemo, useState } from "react";

import { CodeBlock } from "@/components/CodeBlock";
import { CopyButton } from "@/components/CopyButton";
import { BODY, MEASURE } from "@/components/style-tokens";
import { Terminator } from "@/components/ui/marks";
import {
  PLACEHOLDER_SLUG,
  profileAgentPrompt,
  repoAgentPrompt,
  starFacts,
  type StarFacts,
} from "@/lib/agent-prompt";
import { cn } from "@/lib/utils";

type RepoTarget = { kind: "repo"; slug: string; stars?: StarFacts | null };
type ProfileTarget = {
  kind: "profile";
  login: string;
  totalStars?: number | null;
  reposIncluded?: number | null;
};
/** No repository in hand: the prompt resolves one from the checkout's remote. */
type GenericTarget = { kind: "generic" };

export type PromptTarget = RepoTarget | ProfileTarget | GenericTarget;

type Props = {
  apiBase: string;
  siteOrigin: string;
  target: PromptTarget;
};

/** The analyze payload `RepoHero` broadcasts once live data lands. */
type RepoDataEvent = {
  repo?: string;
  total_stars?: number;
  history_kind?: string;
  history_approximate?: boolean;
  history?: { date: string; stars: number }[];
};

/**
 * "Ask an agent to add this to my repo".
 *
 * The copied text is a complete brief, not a one-liner: measured numbers so the
 * agent never invents a statistic, exact paste-ready snippets, the rules that
 * make a published embed correct, and the places to look beyond `README.md`.
 * It is generated by the same pure module that writes the `.md` representation
 * of this page, so what a person copies and what an agent fetches agree.
 *
 * Star facts arrive prerendered and are refreshed from the report's own
 * `gitdebt:repo-data` broadcast — this component never issues a request of its
 * own.
 *
 * The prompt itself is behind a disclosure the reader opens, which is a
 * different thing from content hidden until a timeline runs: the button states
 * plainly what it reveals, it works on the first paint, and nothing on this
 * surface is transparent waiting for an animation to make it visible.
 */
export function AgentReadmePrompt({ apiBase, siteOrigin, target }: Props) {
  const [live, setLive] = useState<StarFacts | null>(null);
  const [open, setOpen] = useState(false);

  const slug = target.kind === "repo" ? target.slug : null;

  useEffect(() => {
    if (!slug) return;
    function absorb(event: Event) {
      const detail = (event as CustomEvent<RepoDataEvent>).detail;
      if (detail?.repo?.toLowerCase() !== slug!.toLowerCase()) return;
      if (!Array.isArray(detail.history)) return;
      setLive(
        starFacts(
          detail.history,
          detail.total_stars ?? null,
          detail.history_kind === "public_star_actions" ||
            detail.history_approximate === true,
        ),
      );
    }
    window.addEventListener("gitdebt:repo-data", absorb);
    return () => window.removeEventListener("gitdebt:repo-data", absorb);
  }, [slug]);

  const prompt = useMemo(() => {
    if (target.kind === "profile") {
      return profileAgentPrompt({
        login: target.login,
        siteOrigin,
        apiBase,
        totalStars: target.totalStars ?? null,
        reposIncluded: target.reposIncluded ?? null,
      });
    }
    return repoAgentPrompt({
      slug: target.kind === "repo" ? target.slug : PLACEHOLDER_SLUG,
      siteOrigin,
      apiBase,
      stars: target.kind === "repo" ? (live ?? target.stars ?? null) : null,
    });
  }, [apiBase, siteOrigin, target, live]);

  const action =
    target.kind === "profile"
      ? "Ask agent to add this to my profile"
      : "Ask agent to add this to my repo";

  return (
    <div>
      <p className={cn(BODY, MEASURE)}>
        Paste it into Claude Code, Cursor, Codex, or any coding agent with your
        checkout open. It carries the measured numbers, the exact snippets, and
        the rules — including replacing an existing star-history widget in place
        rather than stacking a second chart under it.
      </p>

      <div className="mt-5 flex flex-wrap items-center gap-x-6 gap-y-3">
        <CopyButton
          value={prompt}
          ariaLabel="Copy an agent prompt that adds these embeds to a README"
          idleLabel={action}
          successLabel="Prompt copied"
          idleIcon={<Terminator size={14} />}
          variant="primary"
          size="default"
        />
        <button
          type="button"
          onClick={() => setOpen((value) => !value)}
          aria-expanded={open}
          aria-controls="agent-prompt-body"
          className="inline-flex min-h-11 items-center text-[0.875rem] text-ink-2 outline-none transition-colors duration-[--duration-ui] hover:text-signal focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-signal"
        >
          {open ? "Hide the prompt" : "Read the prompt first"}
        </button>
      </div>

      {open && (
        <div id="agent-prompt-body" className="mt-5">
          <CodeBlock
            code={prompt}
            language="markdown"
            label="Agent prompt"
            copyLabel="Copy prompt"
            copyAriaLabel="Copy the agent prompt"
            maxHeightClass="max-h-96"
          />
        </div>
      )}
    </div>
  );
}
